import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./componets/Header";
import HeaderMiddle from "./componets/HeaderMiddle";
import NaVBarTop from "./componets/NaVBarTop";
import SliderBar from "./componets/SliderBar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobNav from "./componets/MobNav";
import Footer from "./componets/Footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <HeaderMiddle/>
        <NaVBarTop/>
        <MobNav/>
        {children}</body>
        <Footer/>
    </html>
  );
}
